---

## Base Vars
nexcess_repo_enabled: "false"

## IWorx Vars
iw_ns1: "ns1.nexcess.net"
iw_ns2: "ns2.nexcess.net"
iw_ns3: "ns3.nexcess.net"
iw_ns4: "ns4.nexcess.net"

## Firewall - Ultimately handled by APF but set this to start
firewall_v4_group_rules:
  401 allow iworx to the world:
    - "-A INPUT -p tcp --dport 2443 -j ACCEPT"

firewall_v6_group_rules:
  401 allow iworx to the world:
    - "-A INPUT -p tcp --dport 2443 -j ACCEPT"
