sudo: required
env:
  matrix:
    - OS_TYPE=centos OS_VERSION=7

services:
  - docker

before_install:
  - sudo docker pull geerlingguy/docker-centos${OS_VERSION}-ansible:latest

script:
  - tests/setup.sh ${OS_VERSION}
