---

- include: iworx-ini.yml
  when:
    - hostvars[inventory_hostname]['interworx::iworx_ini::settings'] is defined
    - mode == "post"

- include: iworx-packages.yml
  when:
    - hostvars[inventory_hostname]['interworx::packages'] is defined
    - mode == "post"

- include: iworx-settings.yml
  when:
    - mode == "post"

- name: Ensure APF Start-on-boot
  service:
    name="apf"
    enabled="yes"
    state="started"
  when:
    - mode == "post"
