---

- include: iworx-ini.yml
  when:
    - hostvars[inventory_hostname]['interworx::iworx_ini::settings'] is defined
    - mode == "post"

- include: iworx-packages.yml
  when:
    - hostvars[inventory_hostname]['interworx::packages'] is defined
    - mode == "post"

- include: iworx-settings.yml
  when: mode == "post"

- include: iworx-php-scl.yml
  when: mode == "post"

- include: iworx-ssl-services.yml
  when: mode == "post"

- include: iworx-multi-ssh.yml
  when: mode == "post"

- include: manage-services.yml
  when: mode == "post"

- name: Ensure APF Start-on-boot
  service:
    name="apf"
    enabled="yes"
    state="started"
  when: mode == "post"

# Dumb fix for mariadb trying to write to a mis-perm'd /dev/shm
- name: Fix /dev/shm Perms
  file:
    path="/dev/shm"
    mode=1777
    owner="root"
    group="root"
  when: mode == "pre"
