---

- name: Grab the InterWorx Backup File
  get_url:
    checksum: "{{ cloudhost_import_backup_checksum }}"
    url: "{{ cloudhost_import_backup_url }}"
    validate_certs: "{{ cloudhost_import_validate_certs }}"
    dest: "/tmp/{{ cloudhost_import_backup_name }}"
    force: true
    mode: 0600

- name: Run the InterWorx Import Process
  command: >
    ~iworx/bin/import.pex
    --control-panel=siteworx
    --ipv4={{ cloudhost_import_ipv4 }}
    --archive=/tmp/{{ cloudhost_import_backup_name }}
