---

- set_fact:
    magento_env_php: "{{ siteworx_docroot }}/app/etc/env.php"

- name: Change MySQL User Passwords
  mysql_user:
    name: "{{ nex_app_unixuser }}_mage2"
    password: "{{ mysql_user_pass }}"
    host_all: true
    config_file: "/root/.my.ansible.cnf"
    state: "present"

- name: Set New MySQL Creds
  command: >
    php -r '
      $env = include "{{ magento_env_php }}";
      $env["db"]["connection"]["default"]["dbname"] = "{{ nex_app_unixuser }}_mage2";
      $env["db"]["connection"]["default"]["username"] = "{{ nex_app_unixuser }}_mage2";
      $env["db"]["connection"]["default"]["password"] = "{{ mysql_user_pass }}";
      file_put_contents("{{ magento_env_php }}", "<?php\nreturn " . var_export($env, true) . ";") || exit(1);
    '
  become: true
  become_user: "{{ nex_app_unixuser }}"

- name: Update Encryption Key
  command: >
    php -r '
      $env = include "{{ magento_env_php }}";
      $env["crypt"]["key"] = "asdf1234";
      file_put_contents("{{ magento_env_php }}", "<?php\nreturn " . var_export($env, true) . ";") || exit(1);
    '
  become: true
  become_user: "{{ nex_app_unixuser }}"

- name: Update Admin URL + Base URLs
  command: >
    php -r '
      $env = include "{{ magento_env_php }}";
      $env["backend"]["frontName"] = "{{ nex_app_admin_location }}";
      $env["system"]["default"]["web"]["unsecure"]["base_url"] = "{{ nex_app_base_url }}";
      file_put_contents("{{ magento_env_php }}", "<?php\nreturn " . var_export($env, true) . ";") || exit(1);
    '
  become: true
  become_user: "{{ nex_app_unixuser }}"

- name: Scrub PII
  command: >
    echo "PII"

- file:
    path: /tmp/test
    state: touch
  become: true
  become_user: "{{ nex_app_unixuser }}"

- file:
    path: /tmp/test2
    state: touch
  become_user: "{{ nex_app_unixuser }}"
  become: true

- file:
    path: /tmp/test3
    state: touch
  become_user: "{{ nex_app_unixuser }}"
  become: yes

- name: New Admin Pass
  command: >
    {{ siteworx_docroot }}/bin/magento
      admin:user:create
      --admin-user="{{ nex_app_username | quote }}"
      --admin-password="{{ nex_app_password | quote }}"
      --admin-email="{{ nex_app_email | quote }}"
      --admin-firstname="{{ nex_app_user_firstname | quote }}"
      --admin-lastname="{{ nex_app_user_lastname | quote }}"
  become: true
  become_user: "{{ nex_app_unixuser }}"

#- name: Update Base URLs
#  command: >
#    /usr/nexkit/bin/nkmagento2 repair
#      --base-url={{ nex_app_base_url }}
#      --secure-base-url={{ nex_app_secure_base_url }}
#      {{ siteworx_docroot }}

- name: Clear Magento Cache
  shell: |
    {{ siteworx_docroot }}/bin/magento cache:clean
    {{ siteworx_docroot }}/bin/magento cache:flush
  become: true
  become_user: "{{ nex_app_unixuser }}"
