---

- name: Change MySQL User Passwords
  mysql_user:
    name: "{{ nex_app_unixuser }}_wp"
    password: "{{ mysql_user_pass }}"
    host_all: true
    config_file: "/root/.my.ansible.cnf"
    state: "present"

## check for existence of a WP install

## update DB user/pass (find right config file)

## update admin creds

## ignore errors until nexkit release
- name: Scrub PII
  command: >
    /usr/nexkit/bin/nkwordpress repair
      --scrub-pii {{ siteworx_docroot }}
  ignore_errors: true
  when:
    - cloudhost_import_scrub_pii

- name: Update Base URLs (This May Be Redundant)
  command: >
    /usr/nexkit/bin/wordpress repair
      --base-url={{ nex_app_base_url }}
      --secure-base-url={{ nex_app_secure_base_url }}
      {{ siteworx_docroot }}

## clear caches
