---

- set_fact:
    siteworx_docroot: "/home/{{ nex_app_unixuser }}/{{ nex_app_domain }}/html"

- name: Make a New MySQL User Password
  command: >
    mkpasswd -d 12 -c 12 -C 12 -s 0 -l 36
  register: mysql_mkpasswd

- set_fact:
    mysql_user_pass: "{{ mysql_mkpasswd.stdout }}"

- include: import-dev-magento.yml
  when:
    - nex_app_type == "magento"
    - nex_app_version == "2"

- include: import-dev-wordpress.yml
  when:
    - nex_app_type == "wordpress"
