---

- name: Create a Work Directory if Renaming
  tempfile:
    state: "directory"
    suffix: "iworx-backup-rename"
  register: workdir

- name: Untar Backup
  unarchive:
    remote_src: true
    dest: "{{ workdir.path }}"
    src: "{{ cloudhost_import_backup_local_filepath }}"

- name: Does the Content Dir Exist?
  stat:
    path: "{{ workdir.path }}/{{ cloudhost_import_rename_old_username }}/{{ cloudhost_import_rename_old_domain }}"
  register: content_dir

- name: Rename Content Dir
  command: >
    mv {{ cloudhost_import_rename_old_domain }} {{ cloudhost_import_rename_new_domain }}
  args:
    chdir: "{{ workdir.path }}/{{ cloudhost_import_rename_old_username }}"
  when: content_dir.stat.exists

- name: Rename Var Dir
  command: >
    mv {{ cloudhost_import_rename_old_domain }} {{ cloudhost_import_rename_new_domain }}
  args:
    chdir: "{{ workdir.path }}/{{ cloudhost_import_rename_old_username }}/var"

- name: Replace Old/New IWORX-META Files
  command: >
    mv {{ item }}
        $(echo {{ item }} | sed "s/{{ cloudhost_import_rename_old_domain }}/{{ cloudhost_import_rename_new_domain }}/")
  args:
    chdir: "{{ workdir.path }}/IWORX-META"
  with_fileglob: "{{ workdir.path }}/IWORX-META/*{{ cloudhost_import_rename_old_domain }}*"

- name: Replace Old/New IWORX-META File Contents
  command: >
    sed -i "s/{{ cloudhost_import_rename_old_username }}/{{ cloudhost_import_rename_new_username }}/" {{ item }}
    sed -i "s/{{ cloudhost_import_rename_old_domain }}/{{ cloudhost_import_rename_new_domain }}/" {{ item }}
  args:
    chdir: "{{ workdir.path }}/IWORX-META"
  with_fileglob: "{{ workdir.path }}/IWORX-META/*"

- name: Rebuild IP Map
  command: >
    md5sum ip-map.json | awk \'{print $1}\' > ip-map.json.md5
  args:
    chdir: "{{ workdir.path }}/IWORX-META"

- name: Move Base Uniqname Dir To New
  command: >
    mv {{ cloudhost_import_rename_old_username }} {{ cloudhost_import_rename_new_username }}
  args:
    chdir: "{{ workdir.path }}"

- name: Create New Import Tarball
  command: >
    tar -czf {{ import_tarball }} {{ cloudhost_import_rename_new_username }} IWORX-META
  args:
    chdir: "{{ workdir.path }}"

- name: Remove Workdir
  file:
    path: "{{ workdir.path }}"
    state: "absent"
