---

- name: Check if Wordpress already installed
  stat:
    path: "{{ siteworx_docroot }}/wp-config.php"
  register: app_wpconfig

- name: Install Wordpress
  shell: >
    /usr/nexkit/bin/nkwordpress install
    --auto-create-database
    --assume-yes
    --admin-username={{ nex_app_username | quote }}
    --admin-password={{ nex_app_password | quote }}
    --base-url={{ nex_app_base_url }}
    --secure-admin
    {{ siteworx_docroot }}
  when: not app_wpconfig.stat.exists
  register: app_installation

- name: Set up Wordpress w3tc Using Redis
  shell: >
    /usr/nexkit/bin/nkwordpress w3tc
    --set-cache-method=redis
    --socket-path=unix:/var/run/redis-multi-{{ nex_app_unixuser | quote }}.redis/redis.sock
    {{ siteworx_docroot }}
  when: app_installation.changed
