---

- name: Enable Interworx SCL PHP Support
  command: >
    nodeworx
    -un
    -c Http
    -a enableMultiplePhp

- name: Find Installed PHP Versions
  find:
    paths: "{{ php_remi_root }}"
    patterns: "php*"
    file_type: "directory"
  register: directory_php_names

- name: Enable PHP Versions
  command: >
    nodeworx
    -un
    -c Http
    -a multiplePhpOptions
    --enabled_php_versions "{{ item.path }}"
    --default_php_version "{{ item.path }}"
  with_items: "{{ directory_php_names.files }}"

- name: Find Latest PHP Version
  shell: >
    ls -1r --sort version "{{ php_remi_root }}" | awk 'NR==1{ print $1 }'
  register: latest_php_version

- name: Set Default PHP Version to Latest
  command: >
    nodeworx
    -un
    -c Http
    -a multiplePhpOptions
    --default_php_version "{{ php_remi_root }}/{{ latest_php_version.stdout }}"

