---
iw_release_channel: 'release'

iw_use_alt_repo_file: false
iw_install_script_url: 'https://updates.interworx.com/interworx/8/install.sh'

iw_use_custom_theme: false

iw_mysql_ver: "12.3"
mariadb_version: "12.3"
iw_php_ver: "8.1"
