---

- name: Deploy / Update InterWorx Servers
  hosts: all
  become: true
  any_errors_fatal: true
  pre_tasks:
    - include: tasks/all.yml mode="pre"
  roles:
    - nexcess.server
    - { role: nexcess.php, php_prefix: "php56", php_single_version: false }      
    - { role: nexcess.php, php_prefix: "php70", php_single_version: false }
    - { role: nexcess.php, php_prefix: "php71", php_single_version: false }
  post_tasks:
    - include: tasks/all.yml mode="post"
