
- name: Perform an InterWorx Site Import
  hosts: cloudhost
  become: true
  any_errors_fatal: true
  pre_tasks:
    - include_vars:
        dir="{{ inventory_dir }}/project_vars"
      ignore_errors: true
    - include_vars:
        dir="{{ inventory_dir }}/region_vars"
        files_matching="{{ nex_zone }}.*"
      ignore_errors: true
    - include_vars:
        dir="{{ inventory_dir }}/host_vars"
        files_matching="{{ inventory_hostname }}.yml"
      ignore_errors: true
    - include: tasks/import.yml mode="pre"
  post_tasks:
    - include: tasks/import.yml mode="post"
